"""add_tag_model

Revision ID: 0fc4cf0f7d6c
Revises: f07fdc350289
Create Date: 2025-01-20 14:37:55.940497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc4cf0f7d6c'
down_revision: Union[str, None] = 'f07fdc350289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('notes_tags',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_notes_tags_note_id_notes')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_notes_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('note_id', 'tag_id', name=op.f('pk_notes_tags'))
    )
    op.drop_column('notes', 'tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('tag', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('notes_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
