"""updated_notes_table_with_unique_constraint_project_id_name

Revision ID: 1b1207c6dd82
Revises: 0fc4cf0f7d6c
Create Date: 2025-01-21 09:52:26.801847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1207c6dd82'
down_revision: Union[str, None] = '0fc4cf0f7d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notes_name', table_name='notes')
    op.create_index(op.f('ix_notes_name'), 'notes', ['name'], unique=False)
    op.create_unique_constraint(op.f('uq_notes_project_id'), 'notes', ['project_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_notes_project_id'), 'notes', type_='unique')
    op.drop_index(op.f('ix_notes_name'), table_name='notes')
    op.create_index('ix_notes_name', 'notes', ['name'], unique=True)
    # ### end Alembic commands ###
