"""add_notes_table

Revision ID: f07fdc350289
Revises: 1c6c823a5c47
Create Date: 2025-01-20 11:29:50.529487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07fdc350289'
down_revision: Union[str, None] = '1c6c823a5c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('publication_details', sa.String(), nullable=True),
    sa.Column('publication_year', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('tag', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_notes_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index(op.f('ix_notes_name'), 'notes', ['name'], unique=True)
    op.create_index(op.f('ix_notes_project_id'), 'notes', ['project_id'], unique=False)
    op.drop_index('ix_projects_id', table_name='projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_projects_id', 'projects', ['id'], unique=False)
    op.drop_index(op.f('ix_notes_project_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_name'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
