name: Build, test and lint the application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Build Docker Container
      run: | 
        docker compose -f docker-compose.yml up -d --build
    - name: Lint code with Ruff
      run: |
        docker compose exec web ruff check --output-format=github .
    - name: Run tests
      run : |
        docker compose exec web pytest
